<?php
$data = array (
  0 => 
  array (
    'cat_id' => '520',
    'cat_name' => '厨房卫浴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '521',
    'cat_name' => '家装五金',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '522',
    'cat_name' => '墙地面饰材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '523',
    'cat_name' => '门窗开关',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '524',
    'cat_name' => '建材品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '529',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '526',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '527',
    'cat_name' => '坐便器',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  8 => 
  array (
    'cat_id' => '528',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '525',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '535',
    'cat_name' => '五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  11 => 
  array (
    'cat_id' => '532',
    'cat_name' => '三角阀',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  12 => 
  array (
    'cat_id' => '533',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '530',
    'cat_name' => '卫浴五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  14 => 
  array (
    'cat_id' => '534',
    'cat_name' => '门锁',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '531',
    'cat_name' => '橱柜五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '538',
    'cat_name' => '饰面板',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '539',
    'cat_name' => '木方',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '536',
    'cat_name' => '细木工板',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '540',
    'cat_name' => '木龙骨',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '537',
    'cat_name' => '集成材',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '541',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  22 => 
  array (
    'cat_id' => '545',
    'cat_name' => '推拉窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '542',
    'cat_name' => '室内门',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '546',
    'cat_name' => '防盗窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '543',
    'cat_name' => '移门',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '547',
    'cat_name' => '开关',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  27 => 
  array (
    'cat_id' => '544',
    'cat_name' => '阳台窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '551',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '548',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '552',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '549',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '553',
    'cat_name' => '浴室柜',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '550',
    'cat_name' => '坐便器',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>