<?php
$data = array (
  520 => 
  array (
    'cat_id' => '520',
    'cat_name' => '厨房卫浴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '520',
    'name' => '厨房卫浴',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '529',
    'name' => '地漏',
  ),
  526 => 
  array (
    'cat_id' => '526',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '526',
    'name' => '水槽',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => '坐便器',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '527',
    'name' => '坐便器',
  ),
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '528',
    'name' => '浴霸',
  ),
  525 => 
  array (
    'cat_id' => '525',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '525',
    'name' => '花洒',
  ),
  521 => 
  array (
    'cat_id' => '521',
    'cat_name' => '家装五金',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '521',
    'name' => '家装五金',
  ),
  535 => 
  array (
    'cat_id' => '535',
    'cat_name' => '五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '535',
    'name' => '五金',
  ),
  532 => 
  array (
    'cat_id' => '532',
    'cat_name' => '三角阀',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '532',
    'name' => '三角阀',
  ),
  533 => 
  array (
    'cat_id' => '533',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '533',
    'name' => '地漏',
  ),
  530 => 
  array (
    'cat_id' => '530',
    'cat_name' => '卫浴五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '530',
    'name' => '卫浴五金',
  ),
  534 => 
  array (
    'cat_id' => '534',
    'cat_name' => '门锁',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '534',
    'name' => '门锁',
  ),
  531 => 
  array (
    'cat_id' => '531',
    'cat_name' => '橱柜五金',
    'measure_unit' => '',
    'parent_id' => '521',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '531',
    'name' => '橱柜五金',
  ),
  522 => 
  array (
    'cat_id' => '522',
    'cat_name' => '墙地面饰材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '522',
    'name' => '墙地面饰材',
  ),
  538 => 
  array (
    'cat_id' => '538',
    'cat_name' => '饰面板',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '538',
    'name' => '饰面板',
  ),
  539 => 
  array (
    'cat_id' => '539',
    'cat_name' => '木方',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '539',
    'name' => '木方',
  ),
  536 => 
  array (
    'cat_id' => '536',
    'cat_name' => '细木工板',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '536',
    'name' => '细木工板',
  ),
  540 => 
  array (
    'cat_id' => '540',
    'cat_name' => '木龙骨',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '540',
    'name' => '木龙骨',
  ),
  537 => 
  array (
    'cat_id' => '537',
    'cat_name' => '集成材',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '537',
    'name' => '集成材',
  ),
  541 => 
  array (
    'cat_id' => '541',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '522',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '541',
    'name' => '其他',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => '门窗开关',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '523',
    'name' => '门窗开关',
  ),
  545 => 
  array (
    'cat_id' => '545',
    'cat_name' => '推拉窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '545',
    'name' => '推拉窗',
  ),
  542 => 
  array (
    'cat_id' => '542',
    'cat_name' => '室内门',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '542',
    'name' => '室内门',
  ),
  546 => 
  array (
    'cat_id' => '546',
    'cat_name' => '防盗窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '546',
    'name' => '防盗窗',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => '移门',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '543',
    'name' => '移门',
  ),
  547 => 
  array (
    'cat_id' => '547',
    'cat_name' => '开关',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '547',
    'name' => '开关',
  ),
  544 => 
  array (
    'cat_id' => '544',
    'cat_name' => '阳台窗',
    'measure_unit' => '',
    'parent_id' => '523',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '544',
    'name' => '阳台窗',
  ),
  524 => 
  array (
    'cat_id' => '524',
    'cat_name' => '建材品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '524',
    'name' => '建材品牌',
  ),
  551 => 
  array (
    'cat_id' => '551',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '551',
    'name' => '浴霸',
  ),
  548 => 
  array (
    'cat_id' => '548',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '548',
    'name' => '花洒',
  ),
  552 => 
  array (
    'cat_id' => '552',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '552',
    'name' => '地漏',
  ),
  549 => 
  array (
    'cat_id' => '549',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '549',
    'name' => '水槽',
  ),
  553 => 
  array (
    'cat_id' => '553',
    'cat_name' => '浴室柜',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '553',
    'name' => '浴室柜',
  ),
  550 => 
  array (
    'cat_id' => '550',
    'cat_name' => '坐便器',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '550',
    'name' => '坐便器',
  ),
);
?>